In [14]:
import pandas as pd
import ydata_profiling as yp
import seaborn as sns
sns.set()
import matplotlib.pyplot as plt
import numpy as np
import itertools
from data_provider import data_provider
from alt_rbm import RBM

In [15]:
provider = data_provider()
ratings = provider.get_ratings()
ratings.describe()

b'943 users\n1682 items\n100000 ratings\n'


rating  unix_timestamp
count  100000.000000    1.000000e+05
mean        3.529860    8.835289e+08
std         1.125674    5.343856e+06
min         1.000000    8.747247e+08
25%         3.000000    8.794487e+08
50%         4.000000    8.828269e+08
75%         4.000000    8.882600e+08
max         5.000000    8.932866e+08

In [16]:
movies = provider.get_movies()
print(movies)

     movie_id                                      title release_date  \
0           0                           Toy Story (1995)  01-Jan-1995   
1           1                           GoldenEye (1995)  01-Jan-1995   
2           2                          Four Rooms (1995)  01-Jan-1995   
3           3                          Get Shorty (1995)  01-Jan-1995   
4           4                             Copycat (1995)  01-Jan-1995   
...       ...                                        ...          ...   
1677     1677                          Mat' i syn (1997)  06-Feb-1998   
1678     1678                           B. Monkey (1998)  06-Feb-1998   
1679     1679                       Sliding Doors (1998)  01-Jan-1998   
1680     1680                        You So Crazy (1994)  01-Jan-1994   
1681     1681  Scream of Stone (Schrei aus Stein) (1991)  08-Mar-1996   

      video_release_date                                           imdb_url  \
0                    NaN  http://us.imdb.com

In [17]:
training_data_df, test_data_df = provider.split_dataframe(ratings)
print(training_data_df)
training_data_df_changed = training_data_df.pivot_table(index='user_id', columns='movie_id', values='rating', fill_value=0)
# Change data to 0 or 1 values
training_data_df_changed = training_data_df_changed.applymap(lambda x: 0 if x < 3 else 1)
training_data = training_data_df_changed.to_numpy()
print(training_data.shape)
print(training_data)
test_data = test_data_df.to_numpy()

      user_id movie_id  rating  unix_timestamp
0         195      241     3.0       881250949
1         185      301     3.0       891717742
2          21      376     1.0       878887116
3         243       50     2.0       880606923
4         165      345     1.0       886397596
...       ...      ...     ...             ...
99995     879      475     3.0       880175444
99996     715      203     5.0       879795543
99997     275     1089     1.0       874795795
99998      12      224     2.0       882399156
99999      11      202     3.0       879959583

[90000 rows x 4 columns]
(943, 1672)
[[1 1 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [1 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [10]:
rbm = RBM(training_data,12,0.1,1000)
rbm.train()

Iteration 0: error is 391827.41221485724
Iteration 1: error is 358078.7680424353
Iteration 2: error is 357490.92105505243
Iteration 3: error is 355924.93920577026
Iteration 4: error is 354075.571840572
Iteration 5: error is 351221.484040983
Iteration 6: error is 341239.6152871111
Iteration 7: error is 338011.1613836579
Iteration 8: error is 340151.84254915715
Iteration 9: error is 345108.02781709476
Iteration 10: error is 339081.52755448414
Iteration 11: error is 303735.12740464136
Iteration 12: error is 298287.9817643986
Iteration 13: error is 297036.12280253257
Iteration 14: error is 294482.4483158874
Iteration 15: error is 263687.78817503306
Iteration 16: error is 263244.632906332
Iteration 17: error is 262256.49469120114
Iteration 18: error is 248862.90003259628
Iteration 19: error is 230962.75545103996
Iteration 20: error is 231750.28131887314
Iteration 21: error is 236767.30633578016
Iteration 22: error is 219386.14474220347
Iteration 23: error is 210829.63730199987
Iteration 24: